push COPY operations as far down as possible

diff --git a/hostapd/Dockerfile b/hostapd/Dockerfile
--- a/hostapd/Dockerfile
+++ b/hostapd/Dockerfile
@@ -7,11 +7,11 @@ RUN cd ./hostapd && patch -u -i ./config.patch ./.config && make -j $(nproc) && 
 
 FROM dadevel/alpine:latest
 ARG TARGETARCH
-COPY --from=hostapd /build/hostapd/hostapd ./bin/
-COPY ./entrypoint.sh ./bin/
-# hostapd -v always exits with return code 1
 RUN apk add --no-cache libnl3 openssl && \
-([ $TARGETARCH != arm ] || apk add --no-cache libgcc) && \
-(hostapd -v || [ $? -eq 1 ])
+([ $TARGETARCH != arm ] || apk add --no-cache libgcc)
+COPY ./entrypoint.sh ./bin/
+COPY --from=hostapd /build/hostapd/hostapd ./bin/
+# hostapd -v always exits with return code 1
+RUN hostapd -v || [ $? -eq 1 ]
 ENTRYPOINT ["entrypoint.sh", "-P", "/dev/shm/hostapd.pid", "-g", "/dev/shm/hostapd", "-G", "app"]
 
